* merged r22035, r22037 and r22075 from trunk: 	  * improved livecd/init scripts to print out and use live instead of cdrom 	  * improved the livecd/init2 to try to remount the media writeable 	  * improved the livecd/init2 to inteligently stick ro and rw markers 	    to the unionfs directories 	  * do not mount a tmpfs over all if a writeable image is found on-the-way 	  * inject noatime options on-the-way

diff --git a/target/share/livecd/init2 b/target/share/livecd/init2
--- a/target/share/livecd/init2
+++ b/target/share/livecd/init2
@@ -4,22 +4,40 @@ echo "T2 live setup (C) Rene Rebe - ExactCODE"
 
 mkdir -p /tmp ; chmod 1777 /tmp
 
-echo "Setting up overlay mounts ..."
+livedev=`sed -n '/[^ ]* \/media\/live/{s/ .*//p; q}' /proc/mounts`
+if mount -n $livedev /media/live -o remount,rw; then
+	echo "Re-mounted /media/live writeable."
+fi
+
+echo "Unionfs overlay setup ..."
 
 dirs='/mnt/live=ro'
-for x in /media/cdrom/live-*.squash; do
-        [ -e $x ] || continue
-        x=${x##*/}; x=${x%.squash}
-        mkdir -p /mnt/$x
-        mount -nt squashfs -o loop /media/cdrom/$x.squash /mnt/$x
-        dirs="/mnt/$x=ro:$dirs"
+rw=0
+for f in /media/live/live-*.*; do
+	[ -e $f ] || continue
+	n=${f##*/}; n=${n%.*}
+	mkdir -p /mnt/$n
+	if mount -nt auto -o loop,noatime $f /mnt/$n; then
+		if grep -q "/mnt/$n .* rw" /proc/mounts; then
+			echo "Mounted $f read-write."
+			dirs="/mnt/$n=rw:$dirs"
+			rw=1
+		else
+			echo "Mounted $f read-only."
+			dirs="/mnt/$n=ro:$dirs"
+		fi
+	else
+		echo "Failed to mount $f!"
+	fi
 done
 
-mkdir -p /mnt/overlay
-mount -nt tmpfs none /mnt/overlay
-dirs="/mnt/overlay:$dirs"
+if [ $rw = 0 ]; then
+	mkdir -p /mnt/overlay
+	mount -nt tmpfs none /mnt/overlay
+	dirs="/mnt/overlay:$dirs"
+fi
 
-mount -nt unionfs -o dirs=$dirs none /mnt/live
+mount -nt unionfs -o noatime,dirs=$dirs none /mnt/live
 
 echo "Finalizing setup ..."
 cat /proc/mounts > /etc/mtab
