* merged 9767,11347,11812,11816 from trunk: added binutils, gcc and linux-header to the Emerge-Pkg blacklist, and improved the message. 	* merged 11369 from trunk: improved Emerge-Pkg by adding an "abort on error" option 	* merged 11521,11561 from trunk: improved Emerge-Pkg by adding a -download-only option 	* merged 13213 from trunk: * improved Emerge-Pkg by adding a -debug switch 	* merged 13111,13112,13213 from trunk: unnested conditionals in Emerge-Pkg/add_if_updated for readability

diff --git a/branches/2.1/scripts/Emerge-Pkg b/branches/2.1/scripts/Emerge-Pkg
--- a/branches/2.1/scripts/Emerge-Pkg
+++ b/branches/2.1/scripts/Emerge-Pkg
@@ -16,12 +16,13 @@
 
 exec 2>&1
 
-blacklist=" glibc glibc23 uclibc 00-dirtree linux24 linux26 "
+blacklist=" 00-dirtree binutils gcc glibc glibc32 uclibc linux24 linux26 linux-header "
 
 options=''
 config=default
 deps=fast
 debug=0
+downloadonly=0
 verbose=1
 ignore_chksum=1
 update=1
@@ -30,6 +31,7 @@ force=0
 rebuild=1
 repositories=""
 system=0
+depth=0
 
 #
 # ----  Functions
@@ -42,7 +44,7 @@ help_msg() {
 	echo
 	echo "Usage: Emerge-Pkg [ -cfg <config> ] [ -dry-run ] [ -force ] [ -noupdate ]"
 	echo "$spacer [ -consider-chksum ] [ -norebuild ]"
-	echo "$spacer [ -deps=none|fast|indirect ]"
+	echo "$spacer [ -deps=none|fast|indirect ] [ -download-only ]"
 	echo "$spacer [ -repository repository-name ] [ -system ] [ pkg-name(s) ]"
 	echo
 	echo "pkg-name(s) are only optional if a repository is specified."
@@ -64,9 +66,11 @@ while [ "$1" ] ; do
 		-deps=*)  deps=${1/-deps=/} ;;
 		-dry-run) dryrun=1 ;;
 		-force)	  force=1 ;;
+		-debug)   debug=1 ;;
 		-noupdate) update=0 ;;
 		-consider-chksum) ignore_chksum=0 ;;
 		-norebuild) rebuild=0 ;;
+		-download-only) downloadonly=1 ;;
 		-repository) repositories="$repositories $2"
 		             deps=none ; shift ;;
 		-system) system=1 ; deps=none ;;
@@ -84,7 +88,7 @@ add_if_req()
 	[ "$verbose" = 1 ] && echo -n "$1"
 
 	if [ "$blacklist" != "${blacklist/ $package /}" ]; then
-                [ $verbose = 1 ] && echo " Update avoided due blacklist."
+                [ $verbose = 1 ] && echo " Automatic update avoided."
 	else
 		[ $verbose = 1 ] && echo " Added."
 		var_append deplist " " "$package"
@@ -109,72 +113,80 @@ add_if_updated()
 
 	[ $verbose = 1 ] && echo -n "checking $package ..."
 	confdir=""
-        for x in package/*/$package/$package.desc ; do
-            if [ -f "$x" ] ; then
-		if [ -z "$confdir" ] ; then
-		  confdir=${x/$package.desc/}
-		else
-		  confdir=X
+        for x in package/*/$package/$package.desc; do
+            if [ -f "$x" ]; then
+		if [ "$confdir" ]; then
+		  echo " Error: Package in multiple trees!"
+		  return
 		fi
+		confdir=${x/$package.desc/}
             fi
         done
+        if [ -z "$confdir" ]; then
+		echo " Error: No such package."
+		return
+	fi
 
-        if [ -z "$confdir" ] ; then
-                [ $verbose = 1 ] &&
-		  echo " No such package."
-        elif [ "$confdir" = X ] ; then
-                [ $verbose = 1 ] &&
-		  echo " Error: Package in multiple trees!"
-        elif [ ! -f /var/adm/packages/$package ] ; then
+        if [ ! -f /var/adm/packages/$package ]; then
 		add_if_req ' Not installed.'
-        else
-                o_ver=$(grep '^Package Name and Version' \
-                                /var/adm/packages/$package | cut -f6 -d' ')
-                n_ver=$(grep '^\[V\] ' $confdir/$package.desc | cut -f2 -d' ')
-                if [ "$o_ver" != "$n_ver" -a "$n_ver" != "0000" ] ; then
-                        add_if_req " New version ($o_ver -> $n_ver)."
-                else
-                        o_ck=$(grep '^\(ROCK Linux\|T2\) Package Source Checksum' \
-                                /var/adm/packages/$package | sed 's,.*: ,,')
-                        n_ck=$( pkgchksum package/*/$package )
-                        if [ $ignore_chksum = 0 -a "$o_ck" != "$n_ck" ] ; then
-				add_if_req " New source checksum."
-			else
-				if [ -f /var/adm/cache/$package ] &&
-				   grep -q '\[BUILDTIME\] .* ERROR' \
-				        /var/adm/cache/$package
-				then
-				    [ $verbose = 1 ] &&
-				      echo -n " Former build was broken."
-
-				    if [ $rebuild = 1 ] ; then
-					add_if_req ''
-				    else
-					[ $verbose = 1 ] && echo " Skipped."
-				    fi
-				else
-				  if [ $debug = 1 ]; then
-				    echo " Installed and up-to-date."
-				  else
-				    echo -ne \
-"\r                                                                          \r"
-				  fi
-				fi
-                        fi
-                fi
+		return
         fi
+
+	o_ver=$(grep '^Package Name and Version' \
+	        /var/adm/packages/$package | cut -f6 -d' ')
+	n_ver=$(grep '^\[V\] ' $confdir/$package.desc | cut -f2 -d' ')
+	if [ "$o_ver" != "$n_ver" -a "$n_ver" != "0000" ]; then
+		add_if_req " New version ($o_ver -> $n_ver)."
+		return
+	fi
+
+	o_ck=$(grep '^\(ROCK Linux\|T2\) Package Source Checksum' \
+	       /var/adm/packages/$package | sed 's,.*: ,,')
+	n_ck=$( pkgchksum package/*/$package )
+	if [ $ignore_chksum = 0 -a "$o_ck" != "$n_ck" ]; then
+		add_if_req " New source checksum."
+		return
+	fi
+
+	if [ -f /var/adm/cache/$package ] &&
+	   grep -q '\[BUILDTIME\] .* ERROR' \
+	   /var/adm/cache/$package; then
+		[ $verbose = 1 ] && echo -n " Former build was broken."
+		if [ $rebuild = 1 ]; then
+			add_if_req ''
+		else
+			[ $verbose = 1 ] && echo " Skipped."
+		fi
+		return
+	fi
+
+	if [ $force = 1 -a $depth = 0 ]; then
+		add_if_req ' Build forced.'
+		return
+	fi
+
+	if [ $debug = 1 ]; then
+		echo " Installed and up-to-date."
+	else
+		echo -ne \
+"\r                                                                          \r"
+	fi
 }
 
 dep4pkg()
 {
+	: $(( depth++ ))
 	for x in `grep '\[DEP\]' package/*/$1/$1.cache 2>/dev/null |
 	          cut -d ' ' -f 2`; do
 		add_if_updated $x
 	done
+	: $(( depth-- ))
 }
 
 # the remaining arguments are packages to be built
-var_append deplist " " "$*"
+for x in $*; do
+	add_if_updated $x
+done
 
 # packages from repositories
 for x in $repositories ; do
@@ -220,12 +232,19 @@ echo "Packages scheduled to build: ${deplist:-none}"
 
 [ $update = 1 ] && options="$options -update"
 
+. config/$config/config
+
 for package in $deplist ; do
-	if ./scripts/Download $package ; then
-		./scripts/Build-Pkg $options $package
+	if ./scripts/Download $package ; then [ $downloadonly != 1 ] && \
+		if ! ./scripts/Build-Pkg $options $package; then
+			if [ $SDECFG_ABORT_ON_ERROR_AFTER -gt 8 ]; then
+				echo "Aborting further builds due to config setting ABORT_ON_ERROR_AFTER."
+				exit 1
+			fi
+		fi
 	else
 		echo "The download for package $package failed!"
-		exit -1
+		exit 1
 	fi
 done
 
