* tagged 7.0-rc2

diff --git a/scripts/Config b/scripts/Config
--- a/scripts/Config
+++ b/scripts/Config
@@ -74,17 +74,6 @@ fi
 cfgtmpdir=src/$config
 
 if [ $do_config_cycle = 0 ] ; then
-	set -e
-	mkdir -p config/$config
-	touch config/$config/{config,packages}
-	set +e
-
-	echo "Aquiring config write lock (may take until other configs finished) ..."
-	# aquire lock
-	exec 200>> config/$config/lock.pid
-	flock 200
-	echo $$ > config/$config/lock.pid
-
 	rm -rf $cfgtmpdir
 	mkdir -p $cfgtmpdir	# src
 
@@ -100,15 +89,24 @@ if [ $do_config_cycle = 0 ] ; then
 		mv src/confdialog.bin.$$ src/confdialog.bin
 	fi
 
-	# don't let Ctrl-C interrupt, because it destroys the configurations
+	# don't accept Ctrl-C because it destroy the configurations
 	trap '' INT
+
+	if [ -d config/$config ]; then
+		echo "Backing up existing config/$config/* ..."
+		mkdir -p $cfgtmpdir/backup
+		cp -a config/$config/* $cfgtmpdir/backup
+		if [ $? -ne 0 ]; then
+			echo "Backup failed, aborting."
+			exit 1
+		fi
+	fi
 
 	echo "T2 $sdever configuration ..."
 	while "$0" -cfg $config $oldconfig $profile -cycle ; do : ; done
 
 	trap INT
 
-	rm config/$config/lock.pid
 	exit 0
 fi
 
@@ -160,6 +158,11 @@ arch=`uname -m | uname2arch`
 current="" ; export SDECFG_ARCH="$arch" ; export SDECFG_EXPERT=0
 menu_this=0 ; menu_current=0 ; menu_counter=0
 menu_stack=x ; menu_back=-1 ; menu_backpos=-1
+
+set -e
+mkdir -p config/$config
+touch config/$config/{config,packages}
+set +e
 
 configtitle="$(printf ' %-50s %6s active packages ]' \
 	"T2 $sdever Configuration - $config" \
